### ISSUE TITLE
PayPal button crashes app

### ISSUE THREAD

**Issue by gavingt** [fujifilmssd/Android-Fujifilm-SPA-SDK-SampleApp#8]
Pressing the PayPal button during checkout crashes our app. It's the same problem across multiple device and Android versions. Here's the stack trace:

`2021-11-05 11:41:14.051 18350-18350/com.simplifieditproducts.picturekeeperconnect E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/braintreepayments/api/BraintreeFragment;
        at com.fujifilm.libs.spa.FujifilmSPASDKActivity$38.run(SourceFile:2924)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.braintreepayments.api.BraintreeFragment" on path: DexPathList[[zip file "/data/app/com.simplifieditproducts.picturekeeperconnect-1R9qLBXTdBTonBH60AVgag==/base.apk"],nativeLibraryDirectories=[/data/app/com.simplifieditproducts.picturekeeperconnect-1R9qLBXTdBTonBH60AVgag==/lib/arm64, /data/app/com.simplifieditproducts.picturekeeperconnect-1R9qLBXTdBTonBH60AVgag==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.fujifilm.libs.spa.FujifilmSPASDKActivity$38.run(SourceFile:2924) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) `

I've tried various things to resolve this, mostly involving adding dependencies. Nothing has worked. I think the root cause is that access to this repository is now forbidden: 

`maven { url  "http://dl.bintray.com/fujifilmssd/maven" }`

**Comment by gavingt** [comment]
Closing this because it only occurs with a special version of the SDK that we were sent to help us with a specific issue.
